version: '3.1'
services:
  services:
    build: .
    container_name: combined-service
    environment:
      - POSTGRES_URL=jdbc:postgresql://us-east-1.b52152fa-97a4-4ebb-87be-812fdf65a3b0.aws.ybdb.io:5433/postgres?ssl=true&sslmode=verify-full&sslrootcert=review-service/root.crt
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=OqTSchvip_ZH-hz7YpYwVs6Wc_Mlij
      - SPRING_DATA_MONGODB_URI=mongodb+srv://user:egy4OdPi4Wyrm99k@cluster0.bgj8zvs.mongodb.net/product_db?retryWrites=true&w=majority
    ports:
      - '8080:8080'
      - '8083:8083'



