version: '3.1'
services:
  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://user:egy4OdPi4Wyrm99k@cluster0.bgj8zvs.mongodb.net/product_db?retryWrites=true&w=majority
    ports:
      - '8080:8080'

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - '8083:8083'
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=review-db
      - POSTGRES_USER=review
      - POSTGRES_PASSWORD=reviewpass


