services:
  - name: review-service
    buildCommand: docker build -t review-service ./review-service
    startCommand: docker run -p 8083:8083 -e SPRING_DATASOURCE_URL=jdbc:postgresql://admin:OqTSchvip_ZH-hz7YpYwVs6Wc_Mlij@us-east-1.b52152fa-97a4-4ebb-87be-812fdf65a3b0.aws.ybdb.io:5433/postgres?ssl=true&sslmode=require&sslrootcert=/etc/secrets/root.crt

  - name: product-service
    buildCommand: docker build -t product-service ./product-service
    startCommand: docker run -p 8080:8080 -e PRODUCT_SPRING_DATA_MONGODB_URI=mongodb+srv://user:egy4OdPi4Wyrm99k@cluster0.bgj8zvs.mongodb.net/product_db?retryWrites=true&w=majority

